spring:
  server:
    port: ${PORT:8080}

    datasource:
      url: mysql://root:qOHKzTJnDYrpanHPgBZlzcOpDWqxRmnP@metro.proxy.rlwy.net:38376/railway
      username: root
      password: qOHKzTJnDYrpanHPgBZlzcOpDWqxRmnP

#  datasource:
#    url: jdbc:mysql://localhost:3306/wwld
#    username: root
#    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


